/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: mohamedhussien (https://sketchfab.com/mohamedhussien)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/batmobil-car-aec9e037fc1c461b9293ede852ac3060
title: Batmobil car
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/batmobile.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.03}>
          <group position={[-8.8, 58.99, 56.46]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <group position={[0.11, 0, -0.05]}>
              <mesh geometry={nodes.Tumbler_Main_Body_body__0.geometry} material={materials.body} />
              <mesh geometry={nodes.Tumbler_Main_Body_00_erged_0.geometry} material={materials['00_erged']} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/batmobile.gltf')
